import { ScrollView, Pressable, StyleSheet, Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { ArrowLeft, Check, Circle, Clock, Plus } from 'lucide-react-native';
import { RootStackParamList } from '../App';
import { usePantry } from '../context/PantryContext';
import { pantryHas } from '../utils/recipeMatching';
import { colors } from '../utils/theme';

type Props = NativeStackScreenProps<RootStackParamList, 'RecipeDetail'>;
export function RecipeDetailScreen({ navigation, route }: Props) {
  const { recipe } = route.params;
  const { pantry, addShoppingItems } = usePantry();
  const missing = recipe.ingredients.filter((ingredient) => !pantryHas(ingredient.name, pantry));
  return <View style={styles.screen}><View style={styles.topbar}><Pressable style={styles.back} onPress={() => navigation.goBack()} accessibilityLabel="Go back"><ArrowLeft size={22} color={colors.ink}/></Pressable><Text style={styles.topTitle}>RECIPE</Text><View style={styles.back}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.emoji}>{recipe.emoji}</Text><Text style={styles.title}>{recipe.name}</Text><Text style={styles.description}>{recipe.description}</Text><View style={styles.time}><Clock size={15} color={colors.forest}/><Text style={styles.timeText}>{recipe.prepTime}</Text></View></View><Text style={styles.section}>INGREDIENTS</Text><View style={styles.ingredients}>{recipe.ingredients.map((ingredient) => { const have = pantryHas(ingredient.name, pantry); return <View key={ingredient.name} style={styles.ingredient}><View style={[styles.check, have && styles.checkHave]}>{have ? <Check size={14} color={colors.white}/> : <Circle size={14} color={colors.muted}/>}</View><View style={styles.ingredientCopy}><Text style={[styles.ingredientName, !have && styles.needed]}>{ingredient.name}</Text><Text style={styles.ingredientAmount}>{ingredient.quantity} {ingredient.unit}</Text></View><Text style={[styles.status, have ? styles.have : styles.need]}>{have ? 'On hand' : 'Need'}</Text></View>; })}</View>{missing.length ? <Pressable style={styles.shoppingButton} onPress={() => addShoppingItems(missing.map((item) => ({ name: item.name, quantity: `${item.quantity} ${item.unit}`.trim() })))}><Plus size={18} color={colors.white}/><Text style={styles.shoppingText}>Add {missing.length} missing to shopping list</Text></Pressable> : <View style={styles.allSet}><Check size={18} color={colors.forest}/><Text style={styles.allSetText}>You have everything you need.</Text></View>}<Text style={styles.section}>METHOD</Text><View style={styles.method}>{recipe.instructions.map((step, index) => <View style={styles.step} key={step}><Text style={styles.stepNumber}>{index + 1}</Text><Text style={styles.stepText}>{step}</Text></View>)}</View></ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, topbar: { height: 62, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' }, topTitle: { color: colors.muted, fontSize: 11, letterSpacing: 1, fontWeight: '800' }, content: { paddingBottom: 36 }, hero: { backgroundColor: colors.ink, padding: 24, alignItems: 'center', marginBottom: 25 }, emoji: { fontSize: 52, marginBottom: 10 }, title: { color: colors.white, fontSize: 27, fontWeight: '800', textAlign: 'center' }, description: { color: '#C7D7CB', fontSize: 14, textAlign: 'center', marginTop: 7, lineHeight: 20 }, time: { marginTop: 15, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#DDEFE2', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 5 }, timeText: { color: colors.forest, fontSize: 12, fontWeight: '800' }, section: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 0.6, paddingHorizontal: 20, marginBottom: 9 }, ingredients: { marginHorizontal: 20, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 7, overflow: 'hidden' }, ingredient: { flexDirection: 'row', alignItems: 'center', padding: 13, gap: 10, borderBottomWidth: 1, borderBottomColor: colors.border }, check: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, checkHave: { backgroundColor: colors.green }, ingredientCopy: { flex: 1 }, ingredientName: { color: colors.ink, fontSize: 15, fontWeight: '700', textTransform: 'capitalize' }, needed: { color: colors.muted }, ingredientAmount: { color: colors.muted, fontSize: 12, marginTop: 2 }, status: { fontSize: 11, fontWeight: '800' }, have: { color: colors.forest }, need: { color: colors.orange }, shoppingButton: { margin: 20, marginTop: 14, height: 49, borderRadius: 6, backgroundColor: colors.forest, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, shoppingText: { color: colors.white, fontWeight: '800', fontSize: 14 }, allSet: { margin: 20, marginTop: 14, flexDirection: 'row', gap: 8, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.mint, padding: 14, borderRadius: 6 }, allSetText: { color: colors.forest, fontWeight: '800' }, method: { marginHorizontal: 20, gap: 14 }, step: { flexDirection: 'row', gap: 12 }, stepNumber: { color: colors.white, backgroundColor: colors.forest, borderRadius: 12, width: 24, height: 24, textAlign: 'center', lineHeight: 24, fontWeight: '800', fontSize: 12 }, stepText: { flex: 1, color: colors.ink, fontSize: 14, lineHeight: 21, paddingTop: 1 } });
