import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Check, Plus, Trash2 } from 'lucide-react-native';
import { usePantry } from '../context/PantryContext';
import { ScreenHeader } from '../components/ScreenHeader';
import { colors } from '../utils/theme';

export function ShoppingListScreen() {
  const { shoppingList, toggleShoppingItem, removeShoppingItem } = usePantry();
  const remaining = shoppingList.filter((item) => !item.checked).length;
  return <View style={styles.screen}><ScreenHeader eyebrow="Bring it home" title="Shopping list" />
    <FlatList data={shoppingList} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={shoppingList.length ? <Text style={styles.counter}>{remaining} {remaining === 1 ? 'item' : 'items'} left to pick up</Text> : null} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyCircle}><Plus size={26} color={colors.forest}/></View><Text style={styles.emptyTitle}>Nothing to buy yet</Text><Text style={styles.emptyCopy}>Missing ingredients from a recipe will land here.</Text></View>} renderItem={({ item }) => <View style={styles.item}><Pressable style={[styles.checkbox, item.checked && styles.checked]} onPress={() => toggleShoppingItem(item.id)} accessibilityLabel={`Mark ${item.name} ${item.checked ? 'not done' : 'done'}`}>{item.checked ? <Check size={15} color={colors.white}/> : null}</Pressable><View style={styles.copy}><Text style={[styles.name, item.checked && styles.done]}>{item.name}</Text>{item.quantity ? <Text style={[styles.quantity, item.checked && styles.done]}>{item.quantity}</Text> : null}</View><Pressable onPress={() => removeShoppingItem(item.id)} hitSlop={10} accessibilityLabel={`Remove ${item.name}`}><Trash2 size={18} color={colors.muted}/></Pressable></View>} />
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, list: { padding: 20, paddingTop: 0, gap: 9, flexGrow: 1 }, counter: { color: colors.muted, fontSize: 13, fontWeight: '700', marginBottom: 5 }, item: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 7, minHeight: 62, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, checkbox: { width: 23, height: 23, borderRadius: 4, borderWidth: 2, borderColor: colors.green, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.green }, copy: { flex: 1 }, name: { color: colors.ink, fontSize: 16, fontWeight: '700', textTransform: 'capitalize' }, quantity: { color: colors.muted, fontSize: 12, marginTop: 2 }, done: { color: colors.muted, textDecorationLine: 'line-through' }, empty: { alignItems: 'center', marginTop: 100, paddingHorizontal: 35 }, emptyCircle: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, emptyTitle: { color: colors.ink, fontSize: 19, fontWeight: '800' }, emptyCopy: { color: colors.muted, textAlign: 'center', lineHeight: 19, marginTop: 7 } });
